name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Deno ${{ matrix.deno }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        deno: ["v1.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Check formatting
        run: deno fmt --check
      - name: Analyze code
        run: deno lint
      - name: Run unit and integration tests
        run: deno test -A --coverage=cov --doc
      - name: Generate coverage report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: deno coverage --lcov cov > cov.lcov
      - name: Upload coverage report
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: cov.lcov
