name: Tests
on: [push, pull_request]
jobs:
  test:
    name: Deno ${{ matrix.deno }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        deno: ["v1.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Deno ${{ matrix.deno }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno }}
      - name: Test algorithms
        run: deno test
      - name: Coveralls (parallel)
        uses: coverallsapp/github-action@v1.1.1
        env:
          COVERALLS_FLAG_NAME: run-${{ matrix.test_number }}
        with:
          github-token: ${{ secrets.github_token }}
          parallel: true
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true